version: "3.1"
services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgresql-backend-shopfleet
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

healthcheck:
  test: ["TCP", "-z", "--", "localhost", "5432"]
  interval: 10s
  timeout: 5s
  retries: 3

volumes:
  postgres-data:
    type: persistent
    storage: 100Gi
  postgres-logs:
    type: local

resources:
  cpu_shares: 1024
  mem_limit: 2Gi

